#!/bin/sh

echo ""
echo "  -.        _.-'      "
echo "  \  ,    .'/.'       "
echo "   \ . . :.-'.-= .-'/ "
echo "     -.:/o  .'-'/ .'  "
echo "       o\o / ._/.'    "
echo "         \| /o|\ .    "
echo "          |'o  . .'.  "
echo "                 --'  "
echo ""
echo "Thank You For Installing Yuna 1.0.2 🤗"
echo ""
