TWEAK_NAME = VioletSpringBoard VioletMusic VioletSpotify

VioletSpringBoard_FILES = SpringBoard/VioletSpringBoard.x
VioletSpringBoard_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
VioletSpringBoard_FRAMEWORKS = UIKit
VioletSpringBoard_PRIVATE_FRAMEWORKS = MediaRemote
VioletSpringBoard_EXTRA_FRAMEWORKS = Cephei

VioletMusic_FILES = Music/VioletMusic.x
VioletMusic_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
VioletMusic_FRAMEWORKS = UIKit
VioletMusic_PRIVATE_FRAMEWORKS = MediaRemote
VioletMusic_EXTRA_FRAMEWORKS = Cephei

VioletSpotify_FILES = Spotify/VioletSpotify.x
VioletSpotify_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
VioletSpotify_FRAMEWORKS = UIKit
VioletSpotify_PRIVATE_FRAMEWORKS = MediaRemote
VioletSpotify_EXTRA_FRAMEWORKS = Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk