GO_EASY_ON_ME = 1

TWEAK_NAME = PomPom
PomPom_FILES = PomPom.x
PomPom_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
PomPom_FRAMEWORKS = UIKit EventKit
PomPom_PRIVATE_FRAMEWORKS = MediaRemote
PomPom_EXTRA_FRAMEWORKS = Cephei
PomPom_LIBRARIES = pddokdo applist

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
