#!/bin/sh

echo ""
echo "  _                ___       _.--. "
echo "  \ .|\..----...-'     -._.-'_.-'  "
echo "  /  '           ,       __.--'    "
echo "  )/' _/     \    -_,   /          "
echo "   -'"  "\_  ,_.-;_.-\_ ',         "
echo "      _.-'_./   {_.'   ; /         "
echo "     {_.-  -'         {_/          "
echo ""
echo "Thank You For Installing Lisa 1.5.1 🤗"
echo ""